/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.signo;

import javax.swing.ImageIcon;

/**
 *
 * @author Xande Barros
 */
public class Signo extends javax.swing.JFrame {

    /**
     * Creates new form Signo
     */
    public Signo() {
        initComponents();
        painelResu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDesc = new javax.swing.JButton();
        painelResu = new javax.swing.JPanel();
        txtSigno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMes = new javax.swing.JTextPane();
        spidDia = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Digite o seu mês: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Insira o dia:");

        btnDesc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDesc.setText("Descubra");
        btnDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescActionPerformed(evt);
            }
        });

        txtSigno.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtSigno.setText("signo");
        txtSigno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtSigno.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Signo:");

        javax.swing.GroupLayout painelResuLayout = new javax.swing.GroupLayout(painelResu);
        painelResu.setLayout(painelResuLayout);
        painelResuLayout.setHorizontalGroup(
            painelResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResuLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addGap(107, 107, 107)
                .addComponent(txtSigno)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        painelResuLayout.setVerticalGroup(
            painelResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelResuLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(painelResuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        txtMes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(txtMes);

        spidDia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        spidDia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spidDiaStateChanged(evt);
            }
        });
        spidDia.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                spidDiaVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelResu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(spidDia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDesc))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDesc)
                    .addComponent(spidDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelResu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescActionPerformed
        // TODO add your handling code here:
        int dia = (int) spidDia.getValue();
        String mes = txtMes.getText();
        
        if(mes.equals("janeiro")){
            if (dia <= 19) {
                txtSigno.setText("Capricórnio");
            } else if (dia >= 20 && dia <= 31){
                txtSigno.setText("Aguário");
            } else {
                txtSigno.setText("");
            }
        } 
        if(mes.equals("fevereiro")) {
            if (dia <= 19) {
                txtSigno.setText("Aguário");
            } else if (dia >= 20 && dia <= 29) {
                txtSigno.setText("Peixes");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("março")){
            if (dia <= 20) {
                txtSigno.setText("Peixes");
            } else if (dia >= 21 && dia <= 31) {
                txtSigno.setText("Áries");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("abril")){
            if (dia <= 20){
                txtSigno.setText("Áries");
            } else if (dia >= 21 && dia <= 30){
                txtSigno.setText("Touro");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("maio")){
            if (dia <= 20) {
                txtSigno.setText("Touro");
            } else if (dia >= 21 && dia <= 31) {
                txtSigno.setText("Gêmeos");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("junho")){
            if (dia <= 20){
                txtSigno.setText("Gêmeos");
            } else if (dia >= 21 && dia <= 30) {
                txtSigno.setText("Câncer");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("julho")){
            if (dia <= 23) {
                txtSigno.setText("Câncer");
            } else if (dia >= 24 && dia <= 31) {
                txtSigno.setText("Leão");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("agosto")){
            if (dia <= 22) {
                txtSigno.setText("Leão");
            } else if (dia >= 23 && dia <= 31) {
                txtSigno.setText("Virgem");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("setembro")){
            if ( dia <= 22) {
                txtSigno.setText("Virgem");
            } else if (dia >= 23 && dia <= 30) {
                txtSigno.setText("Libra");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("outubro")) {
            if (dia <= 22) {
                txtSigno.setText("Libra");
            } else if (dia >= 23 && dia <= 31) {
                txtSigno.setText("Escorpião");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("novembro")) {
            if (dia <= 21) {
                txtSigno.setText("Escorpião");
            } else if (dia >= 22 && dia <= 30) {
                txtSigno.setText("Sagitário");
            } else {
                txtSigno.setText("");
            }
        }
        if(mes.equals("dezembro")){
            if (dia <= 21) {
                txtSigno.setText("Sagitário");
            } else if (dia >= 22 && dia <= 31) {
                txtSigno.setText("Capricórnio");
            } else {
                txtSigno.setText("");
            }
        }
                
        painelResu.setVisible(true);
    }//GEN-LAST:event_btnDescActionPerformed

    
    
    private void spidDiaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spidDiaStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spidDiaStateChanged

    private void spidDiaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_spidDiaVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_spidDiaVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelResu;
    private javax.swing.JSpinner spidDia;
    private javax.swing.JTextPane txtMes;
    private javax.swing.JLabel txtSigno;
    // End of variables declaration//GEN-END:variables

    

    
}
